name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker image
        run: docker build -t natztheking/zenlife-nodejs-app .
      - name: Publish image to docker hub
        run: docker push natztheking/zenlife-nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull imagefrom docker
        run: docker pull natztheking/zenlife-nodejs-app:latest
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name nodejs-app-container -e MONGO_URI=${{secrets.MONGO_URI}} -e NODE_ENV=${{secrets.NODE_ENV}} -e JWT_SECRET=${{secrets.JWT_SECRET}} natztheking/zenlife-nodejs-app:latest
