name: Keep Render Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # allows you to trigger manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: |
          curl -s https://zenlife-back.onrender.com/api/health || echo "Ping failed"
